#!/usr/bin/env bash

# Stop on errors, unset variables, and failed pipeline commands.
set -euo pipefail

# Resolve this script's directory regardless of where it is launched.
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Locate the analysis repository.
PROJECT_ROOT="$(cd "$TEST_DIR/.." && pwd)"

# Keep instrumented compilation outputs separate from ordinary builds.
BUILD_DIR="$PROJECT_ROOT/build_coverage"

# Locate the original source file whose coverage we want to report.
SOURCE_FILE="$PROJECT_ROOT/cascadia++/cascadia/game/entities/tileData.cpp"

# Define the parent directory for generated reports.
REPORT_ROOT="$TEST_DIR/reports"

# Allow the number of parallel build jobs to be overridden.
JOBS="${JOBS:-$(nproc)}"

# Check all tools used by this script.
for tool in cmake ctest g++ gcov lcov genhtml; do
    # Stop with a useful message if a dependency is missing.
    if ! command -v "$tool" >/dev/null 2>&1; then
        # Identify the missing tool.
        echo "Required tool not found: $tool" >&2

        # Return a failure status.
        exit 1
    # Finish checking this tool.
    fi
# Finish checking dependencies.
done

# Verify that the analyzed project's submodule is available.
if [[ ! -f "$SOURCE_FILE" ]]; then
    # Explain how to retrieve the missing source.
    echo "TileData source not found. Run git submodule update --init --recursive." >&2

    # Stop before configuring an incomplete project.
    exit 1
# Finish validating the source file.
fi

# Configure the tests with GCC and coverage instrumentation.
cmake -S "$TEST_DIR" -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_COMPILER=g++ \
    -DENABLE_COVERAGE=ON

# Compile the tests, reusing unchanged build outputs.
cmake --build "$BUILD_DIR" --parallel "$JOBS"

# Locate coverage metadata recursively inside CMake's directory structure.
GCNO_FILE="$(find "$BUILD_DIR" -type f -name '*.gcno' -print -quit)"

# Confirm that compilation generated coverage metadata.
if [[ -z "$GCNO_FILE" ]]; then
    # Explain the missing prerequisite.
    echo "No .gcno files found. Check coverage compilation options." >&2

    # Stop because a coverage report cannot be generated.
    exit 1
# Finish validating coverage metadata.
fi

# Create the parent directory for reports.
mkdir -p "$REPORT_ROOT"

# Keep each run separate so old HTML cannot be mistaken for new results.
REPORT_DIR="$(mktemp -d "$REPORT_ROOT/run_XXXXXXXX")"

# Display the destination before running the analysis.
echo "Coverage output: $REPORT_DIR"

# Enable branch coverage without using the deprecated configuration name.
LCOV_OPTIONS=(--branch-coverage)

# Reset previous runtime counters without deleting compiled files.
lcov --zerocounters --directory "$BUILD_DIR"

# Create a zero-count baseline from compilation metadata.
lcov "${LCOV_OPTIONS[@]}" \
    --capture \
    --initial \
    --include "$SOURCE_FILE" \
    --directory "$BUILD_DIR" \
    --output-file "$REPORT_DIR/initial.info"

# Allow test failures temporarily so coverage can still be collected.
set +e

# Run the complete test suite and save its detailed output.
ctest --test-dir "$BUILD_DIR" --verbose \
    2>&1 | tee "$REPORT_DIR/tests.log"

# Save both exit statuses immediately before another command overwrites them.
RUN_STATUS=("${PIPESTATUS[@]}")

# Restore automatic termination on errors.
set -e

# Stop if the test output could not be saved.
if (( RUN_STATUS[1] != 0 )); then
    # Report a logging failure separately from a test failure.
    echo "Failed to write the test log." >&2

    # Return the logging failure status.
    exit "${RUN_STATUS[1]}"
# Finish checking the log operation.
fi

# Collect the counters generated by this execution of the tests.
lcov "${LCOV_OPTIONS[@]}" \
    --capture \
    --include "$SOURCE_FILE" \
    --directory "$BUILD_DIR" \
    --output-file "$REPORT_DIR/executed.info"

# Include both unexecuted instrumented code and recorded execution counts.
lcov "${LCOV_OPTIONS[@]}" \
    --add-tracefile "$REPORT_DIR/initial.info" \
    --add-tracefile "$REPORT_DIR/executed.info" \
    --output-file "$REPORT_DIR/combined.info"

# Keep only the original TileData implementation, excluding test and Qt code.
lcov "${LCOV_OPTIONS[@]}" \
    --extract "$REPORT_DIR/combined.info" \
    "$SOURCE_FILE" \
    --output-file "$REPORT_DIR/coverage.info"

# Generate an HTML report with line, function, and branch coverage.
genhtml \
    --branch-coverage \
    --legend \
    --title "Cascadia++ — TileData coverage" \
    --output-directory "$REPORT_DIR/html" \
    "$REPORT_DIR/coverage.info"

# Display the exact report location without requiring a particular browser.
echo "HTML report: $REPORT_DIR/html/index.html"

# Make failing tests visible even if report generation succeeded.
if (( RUN_STATUS[0] != 0 )); then
    # Explain that coverage generation does not imply test success.
    echo "Tests failed. See tests.log; coverage may be incomplete after a crash." >&2
# Finish reporting test status.
fi

# Preserve the test runner's exit status.
exit "${RUN_STATUS[0]}"